### ISSUE TITLE
Feature list / tweaking bugs for phylogenomic dataset browser 0.9 release

### ISSUE THREAD

**Issue by lonelyjoeparker** [lonelyjoeparker/qmul-genome-convergence-pipeline#43]
Features needed:
- [x] #46 Phylogeny stats
    - [x] #59 **PARSE NEXUS TREEFILES**
    - [x] #57 remaining tree stats if time
    - [x] #58 phylogeny view stats scrollpane, text export
- [x] About and version string
- [x] Name to Context
- [x] Update github help.md
- [x] ~~Tooltip help string?~~ _Push back to 0.9.1+_
- [x] additional features:
    -  [x] ~~font size?~~ _Push back to 0.9.1+_
    -  [x] ~~colouring?~~ _Push back to 0.9.1+_
    -  [x] #42 translation behaviour?
- [x] Add charting behaviour #52 
    - [x] For alignments
    - [x] ~~For phylogenies~~  _Push back to 0.9.1+_
  - [x] #39 Scrolling phylogeny 
 - [X] #36 Correct table header widths
 - [x] #53 Use system hotkeys 
 - [x] #54 Track alignment pane position between AA and NT windows.

Bugs to fix:
- [x] Translate() method using expanded hash
- [x] 'phylogeny display here' label in phylogeny tab
- [x] text export in menu

**Comment by lonelyjoeparker** [comment]
Addressed in v0.8 prerelease (up to and including https://github.com/lonelyjoeparker/qmul-genome-convergence-pipeline/commit/ab766d123c623f770b81f09d2c067b9752bfcdbd today):

* About and version string
* Name to Context
* Update github help.md
* Tooltip help string?

**Comment by lonelyjoeparker** [comment]
Outstanding issues (from above):
* Colouring
* Tooltip / buttons for phylogeny tab
* translation full hash options (see also https://github.com/lonelyjoeparker/qmul-genome-convergence-pipeline/issues/42; implemented partially by updated translation hash init in https://github.com/lonelyjoeparker/qmul-genome-convergence-pipeline/commit/2d7e92f06dde4426a55748a58da1b07e592deecc but not yet accessed by CONTEXT or GCP)
* clean up phylogeny tab

Other outstanding issues:

* https://github.com/lonelyjoeparker/qmul-genome-convergence-pipeline/issues/39 : Phylogeny scrollpane
* https://github.com/lonelyjoeparker/qmul-genome-convergence-pipeline/issues/36 : Phylogeny table widths

**Comment by lonelyjoeparker** [comment]
Also #46 phylogeny statistics
